name: Test Using Emulation and Docker Image

env:
  platforms: linux/amd64

on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
    paths-ignore:
      - 'docs/**'
      - '**/*.md'

jobs:
  TestEmulated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0
      # build tester image
      - name: Build image
        id: build_image
        run: |
           docker build --target tester -t ebpf-nat64-tester:latest .
      # ebpf-nat64 tests
      - name: Run tests
        id: run_tests
        run: |
           docker run --rm --privileged ebpf-nat64-tester:latest /app/entrypoint.sh --addr-port-pool 5.5.5.5:1000-2000 --log-level error --test-mode
